version: '3.9'
services:
  db:
    image: postgres:latest
    container_name: postgres-swahili
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=mypassword
    ports:
      - "5432:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/swahili_hate
      - /swahili_hate/static
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=True
